"""Initial migration.

Revision ID: 0a34d4a139af
Revises: 
Create Date: 2023-02-27 11:32:58.263347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a34d4a139af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recive', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('send', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['send'], ['register.id'], name=op.f('fk_requests_send_register')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests'))
    )
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_register_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_register_email'), type_='unique')

    op.drop_table('requests')
    # ### end Alembic commands ###
