"""Initial migration.

Revision ID: 2457a0a46877
Revises: 5c449e5be6c6
Create Date: 2023-02-27 12:12:20.653539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2457a0a46877'
down_revision = '5c449e5be6c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friends', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['register.id'], name=op.f('fk_friends_register_id_register')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friends'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
