"""Initial migration.

Revision ID: 5573b876a458
Revises: 55ae29d54a17
Create Date: 2023-02-27 21:13:32.064625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5573b876a458'
down_revision = '55ae29d54a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('public', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_column('public')
        batch_op.drop_column('private')

    # ### end Alembic commands ###
