"""Initial migration.

Revision ID: 55ae29d54a17
Revises: 2457a0a46877
Create Date: 2023-02-27 17:46:47.978291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ae29d54a17'
down_revision = '2457a0a46877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_number', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('address1', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address2', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('postcode', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('Country', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('education', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_column('education')
        batch_op.drop_column('Country')
        batch_op.drop_column('state')
        batch_op.drop_column('postcode')
        batch_op.drop_column('address2')
        batch_op.drop_column('address1')
        batch_op.drop_column('mobile_number')

    # ### end Alembic commands ###
