"""Initial migration.

Revision ID: 5c449e5be6c6
Revises: 0a34d4a139af
Create Date: 2023-02-27 11:35:34.543462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c449e5be6c6'
down_revision = '0a34d4a139af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
