"""Initial migration.

Revision ID: bcb6d883e19b
Revises: eed7ea2f6852
Create Date: 2023-03-01 13:34:26.855192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb6d883e19b'
down_revision = 'eed7ea2f6852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('register_id', sa.INTEGER(), nullable=False),
    sa.Column('friend', sa.INTEGER(), nullable=False),
    sa.Column('msg', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['register_id'], ['register.id'], name='fk_chat_register_id_register'),
    sa.PrimaryKeyConstraint('id', name='pk_chat')
    )
    # ### end Alembic commands ###
